---
title: Code
date: 2018-04-23
---

## Templates for $\mathrm{\LaTeX}$ and R Markdown

Document styles, not too complicated, but with a personal touch. Now [available on Github](https://github.com/mikedecr/document-templates). 

- $\mathrm{\LaTeX}$ article (`pdflatex`). [View example](https://github.com/mikedecr/document-templates/blob/master/tex/pdflatex/article/pdflatex-article.pdf)
- R Markdown article (`pdflatex`). [View example](https://github.com/mikedecr/document-templates/blob/master/rmd/pdflatex/rmd-pdflatex-article.pdf)
- TBD: `memoir`-class documents (e.g. for dissertations). 
- TBD: $\mathrm{\LaTeX}$ and R Markdown documents built with `xelatex`.

Templates use Minion and Myriad typeface packages, which won't be set up for `pdflatex` unless you have [done the work](https://github.com/sebschub/FontPro) for that. If you want the quick route to enabling those typefaces, build your document with `xelatex` instead of `pdflatex` (but N.B. `xelatex`'s typography isn't as strong). If you don't want either, change the typeface package.



## Workshops: Math Camp and $\mathrm{\LaTeX}$

Materials for these workshops are all open source and available on Github:

- **[Math camp](https://github.com/mikedecr/math-camp-2018) for political science graduate students.** Introduces important concepts in algebra/pre-calculus, basic linear algebra, set notation and theory, derivative and integral calculus, and probability. 
- **[$\mathrm{\LaTeX}$](https://github.com/mikedecr/latex-workshop-2018) workshop.** What is $\mathrm{\LaTeX}$, example documents, bibliographies, beamer, workflow integration with statistical software, R Markdown, and Xaringan



## Sublime Text User Settings

The [Sublime Text](https://www.sublimetext.com/) editor is a great mix of [extensibility](https://packagecontrol.io/) and usability for social science, but its [text-based settings](http://docs.sublimetext.info/en/latest/customization/settings.html) can be daunting for the uninitialized and a rabbit hole for the detail-obsessed.

My settings can be viewed and pilfered at will from [Github](https://github.com/mikedecr/sublime-user-settings). Highlights include:

- Keybindings (primarily for R and $\mathrm{\LaTeX}$) and associated macro files.
- Code snippets for various languages---mainly R and $\mathrm{\LaTeX}$, but some for Stan, Stata, HTML, and Markdown.
- Modified `solarized` color schemes, available in light, dark, and lastly "gray," which is a weird hybrid of a few color schemes.



## Github

This website is continuously undergoing revisions, and some useful code may have no home on this page. Feel free to dig around in my [Github repositories](https://github.com/mikedecr).


