---
title: "Day 2: Graphics"
author: "Michael DeCrescenzo"
description: "Graphics in R using ggplot2"
date: '2018-02-01'
slug: 553-day2-graphics
categories: ["R", "PS553", "Teaching"]
tags: []

draft: true
---


# Sarah

- why
  + helpful to see what the data look like
  + tell persuasive stories
  + important that you know relevant features of the data
  + shape of the data indicate appropriate modeling
    * *long right tails, logging*
- Understanding data
  + *know thy data*
  + unit of analysis
  + number of observations
  + where is there variation
  + units of measurement
  + values within variable
  + missing data
  + relationships among variables
- summary statistics
  + `summary, cor, quantile`
  + `table()`
  + `group_by() %>% summarize()`
  + `group.CI()` or whatever it's called
- simple base plots
  + scatterplots
  + histograms
  + kernel density estimation
- *transition to ggplot*
  + *data, axis aesthetics, geoms, scales, theme options*
  + *ggplot() and qplot() functions. qplot() is just confusing IMO* 
  + *justify gglot*
    * *more with less code*
      - *grouping*
      - *faceting*
      - *legends*
    * *prevents you from doing stupid shit*
      - multiple y axes
      - bad aesthetic choices (multiple DVs at once)
    * *saving is easier*
    * *they look better*
    * *easy to customize your own cute theme (help guides online but don't include a link [don't want them to get sidetracked] but don't overdo it)*
- *once in GGplot*
  + scatterplots (two continuous)
  + dot plots (factor x continuous) *replace bar plots*
  + line graphs (two continuous where order matters, need to be sorted)
  + don't use pie charts
    * *anything in a pie chart should be a bar graph*
  + bar graphs
    * *only things in a bar graphs should be counts and proportions, IMO*
    * *stacks of things that have a zero lower bound*
    * *don't use them for 1-5 scales*
    * *IMO don't use them for treatment effects. This makes no sense*
    * *they also make you use error bars on top of columns for CIs, which looks fugly IMO*
  + *coefficient plots (wait on this?)*
  + *acf pacf* with some package
- aesthetic choices
  + contrasting colors may be bad for colorblindness
  + gradients of the same color may be good for computer screens, but maybe not for print or shitty projectors
  + does the journal accept color? might want to think about ways around color
  + resources
    * http://mkweb.bcgsc.ca/colorblind/
    * http://www.somersault1824.com/tips-for-designing-scientific-figures-for-color-blind-readers/
    * http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3
    * http://ggplot2.tidyverse.org/reference/scale_brewer.html
    * `viridis`! *but don't overdo it*
- saving
  + base
    * `pdf("file.pdf", width =, height =); par(whatever); plot(whatever); dev.off()`
  + ggplot
    * `ggplot(whatever); ggsave(whatever, width =, height =)`
- Complex data analysis
  + *note to self: learn about arm, rms*
    * *if you don't get to this, just say that you don't do regressions that much, and you don't do frequentist regression when you do, LOL*
  + regression functions
    * transform within function call (logs, interaction, factor dummies)
  + glms
    * ols: y = (XB)
    * glm: link(y) = XB; y = inv_link(XB)
      - logit(p(y)) = XB. invlogit(XB) = p(y)
  + interpreting model output
  + generating model output
    * table packages
      - list: https://stackoverflow.com/questions/5465314/tools-for-making-latex-tables-in-r
      - stargazer: https://cran.r-project.org/web/packages/stargazer/vignettes/stargazer.pdf
      - apsrtable: https://cran.r-project.org/web/packages/apsrtable/apsrtable.pdf
      - *I like xtable and texreg*
      - there are pros and cons. Some are better for regression, summary statistics, just other tables you might make (xtable)
    * `arm::coefplot`
    * `coefplot` package
    * `coefplot2`
    * I'd say: coefplots by hand using `broom` and `ggplot2`. Easy for jamming multiple models together
      - http://varianceexplained.org/r/broom-intro/
      - https://arxiv.org/pdf/1412.3565.pdf
    * *I've seen people do coefplots using base graphics and it's like half the entire file. It's fugly*
  + marginal effects
    * effects
    * zelig
    * *sjplot*
  + post-estimation
    * residuals 
    * (most models: normal on the index. OLS index = link)
    * *Log Likelihood* (coef.test? where are there model things for GLMs?)
    * *information criteria: AIC, WAIC*
      - meant to estimate out-of-sample performance
      - see McElreath videos
      - since every fit is a combination of true + noise (even assuming perfect model)
    * don't BIC
      - neither Bayesian nor IC


Improving on Sarah

- how tidy data becomes good for ggplot
  + stacking factors for grouping aesthetics
- nail grouping as a benefit
  + if you have multiple countries, multiple states, multiple datasets
  + you *can* gather multiple DVs, but then you can't get different axis labels, so do this only for private use OR with conceptually related variables for public use
    * *use var-ecm graphic as a bad example*
- What to do about model graphics
  + a simple regression example
  + use broom for coefficient plot
  + sjplot for a simple marginal effects?
  + broom: learn how `glance` works
  + `predict(new.data)`
  + effects?
  + margins?
  + arm?
  + rms?
  + *and then save complex predictions for modeling day?*
- Other graphics tips
  + confidence interval things:
    * steep change look like narrow confidence intervals
    * confidence intervals are *vertical* for a given x value (find tumblr example)
  + log(0)
    * are they counts? use a count model instead of a log
    * are they unequal probability? use an ordinal model
- stata vs R
  + if you have a simple OLS or GLM and want to do a simple prediction or simple MFX, Stata does this pretty well
  + R is way better for visualizing multiple models together (tidy data, broom, ggplot)




# Brief Introduction to Base Graphics


## Basic plotting

`plot()`

`hist()`

Bar charts, box plots, all easier in other software


## some handy tools

pch

linetype


# Graphics packages, pros and cons


# ggplot2


## aesthetics

## geoms

## scales

## themes and theme elements



## Dos and Don'ts

Multiple Y axes




# Examples using ggplot2



# out there things

heatmaps, network stuff (ggraph), see drob posts

patchwork, ggforce, (?)ggproto, all the pederson stuff

# Graphics packages revisited



