---
title: Conclusion
description: "Final notes on R"
author: "Michael DeCrescenzo"
date: '2018-07-02'
slug: "811-conclusion"
categories: ["R", "ps811", "Teaching"]
tags: []
---


# Comparing and contrasting R and Stata

As you continue working with these softwares, you will see more about how these languages are similar and different. There are definitely *some* similarities. The REPL interface (commands are evaluated instantly and results displayed in a console) is a big one. This means you don't have to compile an entire file of code before you can run it. Yay! 

The differences between R and Stata have benefits and drawbacks. Here is some rapid-fire accounting of some differences. 

R is free and open source. 

- Pro: When you lose your university access license to Stata (which you will, eventually), you can still use R.
- Con: Some of the stuff in R may lower quality than the stuff in Stata. Granted, most of the stuff in R you use works just as well as Stata, but there is really nothing stopping some jerk from writing some sloppy code and putting it out there. Wisdom of the crowds generally holds though: if an R tool is popular, you can count on it to be reliable. There are *lots* of smart people using and constantly improving R!


R is a fully formed programming language.

- Pro: R makes it very easy to directly access data as vectors, matrices, and dataframes with a coherent and vertically integrated programming syntax.
- Pro: R operates with *functions* rather than mere *commands*. In R, if I had the functions `f()`, `g()`, and `h()`, I could write `f(g(h(x)))` in one line of code and it just works.
- Con: This makes R a little tougher to learn at first for those with less computing experience.


R is object-oriented.

- Pro: this lets R be very flexible.
- Pro: You can load and manipulate multiple datasets at once without being confined to one data table. 
- Con: This makes accessing variables within datasets more difficult, because you have to specify *which* dataset to look inside of. We will cover this in the future. Luckily, the `tidyverse` provides tools for making this easier.
- Con: This also makes R slower than Stata, generally speaking. This is because R has to check to make sure that the commands you want to run make sense (checking data types, sizes of objects, and so on). You generally won't notice this unless you work with larger datasets. When your dataset is truly massive, there are ways to use R as a front-end to interact with other programming languages, such as `RSQL` to talk to SQL from R.


R's interface is less graphical than Stata. It's all about the code.

- Pro: This makes replication easier (or, harder to mess up) in R, because there is less dependence on pointing-and-clicking to create analysis and graphics. 
- Con: For newcomers who are used to seeing their data in front of them as a spreadsheet, this makes R more psychologically difficult to pick up than Stata.
- Con: R syntax is more "programmy" and less English-seeming. The drawback of this is that it is complicated *at first*. The benefit of this is that it is simpler in the long run, because the rules of the syntax impose long-run structure and coherence in the R language.

