---
title: "PoliSci 811: R Introduction"
description: "Brief introduction to this semester's R lessons. READ BEFORE CLASS."
author: "Michael DeCrescenzo"
date: '2017-11-29'
slug: 811-intro
categories: ["R", "ps811", "Teaching"]
tags: []

# draft: true
---


Welcome to the online lessons for PS 811: Introduction to Statistical Computing for Political Science. This series of blog posts contain instructional notes for using R for political science research.


# A little about R

R is not the only program out there for doing statistical programming, so let's begin by talking about what makes it unique. 

Compared to other popular statistical software for the social scientists (such as Stata), R stands out as a more general programming language. Said another way, you should think about R as more than a set of *commands* that are punched into a program; it is a collection of functions and routines that can be used to build more complex and powerful tools for a broader set of computational uses. This has some trade-offs; namely, it requires some more up-front investment by the user. That being said, these investments pay off in several ways---in future R use, the use of other programming languages, and even learning more advanced mathematics.

R is an "object-oriented" language, which essentially means that everything is an *object* that contains either data or code to manipulate data. Functionally, this makes R extremely flexible for use in statistics. It also helps you learn other similar languages that have advantages over R for certain uses---Python for web scraping and GIS, C++/Stan for Bayesian analysis, and so on. 

Some softwares are better suited to certain tasks than others. For example,  Stata has historically been a stronger program than R for time series analysis (though time series analysis in R has seen dramatic improvement in recent years). However, R has much more flexibility than Stata to modify what an analysis is doing, allowing more explicit control over data manipulation, modeling, graphics, and workflow integration across programs. To be slightly more specific, R will make fewer assumptions about what the user wants to do than Stata does. This tendency has certain benefits and drawbacks. Many typical statistical routines are easier to perform in Stata than in R. R makes it easier to go beyond the typical routine, but it requires that the user know more details about the typical routine in order to extend it effectively.

I'll put it a different way and provide an example. Just about anything that you can do in Stata, you can also do in R. *But*, many things that are simple in Stata can be a little weird in R. This is because R has a tendency to reveal something about "typical" routines: just because the routines are typical does not necessarily mean they are *simple*, or *default*, or free of complex assumptions. Those details and assumptions aren't *gone* in Stata; they are only hidden. For example, estimating a linear regression in Stata using robust (that is, [heteroskedasticity](https://en.wikipedia.org/wiki/Heteroscedasticity)-consistent) standard errors is as simple as `reg y x, robust`. If you try to use robust standard errors in R, however, you come face to face with something that is not apparent when using Stata: there are [many types of heteroskedasticity-consistent standard errors](https://www.rdocumentation.org/packages/sandwich/versions/2.4-0/topics/vcovHC), and R requires the analyst to choose which estimator they want. Stata, in short, makes a default choice for the user. As a result, political science is full of "robust" standard errors that reflect Stata's default choice of estimator rather than the researcher's intentional choice.

In summary, R sometimes puts more demands on the user's knowledge of statistics and programming. I generally prefer this for a few reasons. I have an anxious need to feel reassured that I know what I'm doing, and part of that is knowing what my statistics (and in turn, my software) are doing. I need the details. I also like to use more technical programming tricks to interact with my data at times. But this is just me. Not every user will find this degree of flexibility and detail helpful for their needs, and loads of brilliant social scientists use Stata to enormous success. As you learn more about statistics, about the research you intend to do, and about the tools available to you, (and perhaps about yourself), you will have to make these software decisions for yourself---or someone else will make the choice for you!



# Bottom-up theory

Because R is a more flexible and extensible programming language than Stata is, it often requires greater familiarity with a wider set of programming concepts. This course will touch on some of these concepts as we go, but rather than hammering them to death, I will instead aim to provide resources for further learning along the way.

Some of these concepts may seem tedious at first, e.g. variables and functions. We discuss these not because you cannot be trusted to understand these concepts *in general*, but because these concepts relate to programming in not-always-obvious ways. (For example, what is the difference between a global and local variable? Or, how can a function return "random" results even if you keep the inputs the same?) The mathematical world and the programming world exhibit many similarities, and understanding how these realms relate will help you become a more skilled programmer, a stronger mathematical thinker, and a better statistical analyst.

Having said that, my intent is never to overburden new R users with too much theory. The aim of this course is to build a foundation with R, providing enough structure for users with different levels of R ambition to continue with *their own learning* in the future.


# Pedagogical note

Because R is open-source and very flexible, there is a *diversity of methods* that users can employ to accomplish similar goals. That is, there are often many ways to do the same thing. As a *teacher* of R, this makes things difficult. Instructors, being experienced R users, see the diversity of methods as a benefit. But for new R users, this diversity can be daunting and confusing. When you're learning a new language, sometimes you just want to be told what works.

We have a short time to cover as much quality R as we can, so we have to make some choices about what material to emphasize. Here is the approach we will take. (I confess that my thinking is heaviliy influenced by some blog posts by David Robinson about teaching R, including but not limited to [here](http://varianceexplained.org/r/teach-tidyverse/)).

- Rather than give you abstract exercises to demonstrate concepts in a vacuum, we'll create realistic scenarios using real data as much as we can. 
- I won't force you to slog through difficult problems using underpowered tools for the gratuitous purpose of "getting you to appreciate the finer points of the language" or whatever. Nor will we contrast old and new tools or painstakingly catalog how how multiple approaches lead to the same end result. Instead, we will jump quickly into tools that I believe you will actually use in the future.
- Relatedly, this means we'll be following a philosophy of *doing as much as we can with as few powerful tools as possible*. Let's define a "powerful" tool as one that performs a complicated task with a simple interface. That's the sweet spot. 
- Hopefully this *makes R exciting to learn* because we can do real heavy lifting with it *soon*, rather than "graduating" to fun stuff after boring you with annoying stuff. 

To help us achieve these goals together, I have made the strategic decision to focus this course on the `tidyverse` suite of data manipulation packages, including `ggplot2` for graphics. There are several other "families" of data manipulation and graphics approaches, including "base R," which is where most R courses begin. Those courses then shift to other approaches after students have been beaten into submission by the inefficiency of base R. My attitude is that you are highly unlikely to use weak tools once you discover powerful tools, so I don't want to use your time on them. Put simply, the Tidyverse is the fastest route to accomplish my goals for this course---to teach you R that is useful, realistic, simple, powerful, and fun. 


# Course structure

We will work through this course using three tools: online notes, in-class lectures, and take-home exercises.

Online notes will be the "most complete" accounting of useful R concepts, functions, and lessons. I hope that these will be a permanent resource that you can always come back to. Online notes will be easiest to read on this website, but source code for all lessons will also be available on my [Github page](https://www.github.com/mikedecr) as `.Rmd` files. We'll divide the material for this course across four documents (*not including* this page). You should review each lesson ***before*** its corresponding lecture day. 

- For the first week of R lecture, read this [overview of some basic R material](811/811-basics) and [this lesson on data manipulation](811/811-data). The first document covers the absolute basics---installing R, simple commands---and the second document covers data manipulation using `tidyverse` routines.
- For the second week, we will cover [graphics](811/811-graphics), with a particular focus on `ggplot2`.
- Week 3 covers [statistical analysis](811/811-analysis), including model estimation, generating model summaries and post-estimation analysis, and discussing how to incorporate your results into your written work using workflow tools. This lesson will also contain some material on advanced R tools and routines.

Lecture will be a guided walk-through of each week's material. They will cover *incomplete selections* from the online notes, so it is important to preview the notes before class. We will try to leave as much in-class time to work on take-home exercises as possible.

The take-home exercises will reinforce each week's material using an extended analysis of one dataset. These exercises are required and should be submitted on the *Thursday* following each lesson. "Solutions" will be made available the following day. For feedback on the exercises, I prefer we schedule an office hours meeting. (Per the syllabus, office hours are by-appointment). 

# Datasets

The dataset we will use for online notes and in-class lectures is the American National Election Study, which is a long-running academic survey of U.S. voting and public opinion. Specifically, we will work with the "[cumulative data file](http://electionstudies.org/studypages/anes_timeseries_cdf/anes_timeseries_cdf.htm)," which contains interviews from survey respondents for presidential and midterm campaign seasons since 1948. To obtain the data, make an account on [electionstudies.org](http://electionstudies.org/) and download the cumulative data file before the first in-class lesson. Make sure your download includes the codebook. You should take care of this *well in advance* of our first R lecture. If you encounter difficulties, get it touch with me *after* trying to troubleshoot your problem using the website's instructions ;-) .

Take-home exercises will use the [Database on Ideology, Money in Politics, and Elections](https://data.stanford.edu/dime#download-data), which contains information on campaign contributions for U.S. elections organized at by candidate-cycles. There are many data files in the DIME, but you should only download the data file called `dime_recipients_all_1979_2014.csv.gz`. Download the codebook as well.



# Seeking help, or, My role as instructor

My goal is to get you started with R, but I cannot make you an expert. You learn R mostly by doing it, and over the long run, you will learn far more from the internet than you will from me. This is as it should be---the internet is your friend. Being "good at R" means (to a certain extent) knowing what to do when you mess up, learning how to Google the error message, and learning to avoid past mistakes. To that end, when you encounter problems with R, I encourage you to start by seeking your own help online. Training yourself to find online solutions is an invaluable skill for R (and any software), so you should practice while you can. Of course, you can contact me if you find online resources to be confusing. 

Sources like Stack Overflow are great for working through R problems. So is Twitter. The most prominent R developers are active on both. 