---
title: "Political Science 270: Understanding Political Numbers"
date: "2016-05-05T21:48:51-07:00"
---

# Schedule

```{r setup, include = FALSE}
library("knitr")
library("here")
library("tidyverse")

opts_chunk$set(eval = TRUE, echo = FALSE, 
               warning = FALSE, message = FALSE, 
               cache = FALSE, cache.path = here::here("lectures", "cache", "01-"), 
               fig.align = "center", # eval.after = 'fig.cap', 
               fig.retina = 2, dpi = 100)
```


```{r build-table}
science <- 
  bind_rows(
    data_frame(date = "January 23", topic = "Introduction",
               reading = "[Syllabus](../reading/readings-270-s19#jan-23)",
               # reading = "",
               assignment = "",
               slides = "")
  ) %>%
  print()


full_table <- bind_rows(science) %>%
  rename_all(str_to_title) %>%
  kable() %>%
  print()
```

```{r gt-try}
library("lubridate")

dates <- c("2019-1-23", "2019-1-28", "2019-1-30", "2019-2-4", "2019-2-6", "2019-2-11", "2019-2-13", "2019-2-18", "2019-2-20", "2019-2-25", "2019-2-27", "2019-3-4", "2019-3-6", "2019-3-11", "2019-3-13", "2019-3-25", "2019-3-27", "2019-4-1", "2019-4-3", "2019-4-8", "2019-4-10", "2019-4-15", "2019-4-17", "2019-4-22", "2019-4-24", "2019-4-29", "2019-5-1", "2019-5-6") %>%
  as_date() %>%
  format('%B %d') %>%
  print()

date_column <- str_glue("{rep(c('(Wed)', '(Mon)'), length(dates) / 2)} {dates}") %>%
  as.character() %>%
  print()

lecture_topics <- c("Intro", "Evidence", "Theories and hypotheses", "Measurement and causality", "Data", "Graphics", "Graphics in R", "Averages, expectations, aggregation", "Variation and randomness", 'Relationships as "conditional expectations"', "Linear regression", "Statistical significance", "Unpacking regression", "Multiple regression", "Finding and cleaning data", '"Dummies": Indicators and interactions', "Nonlinear relationships", "Evaluating public policy", "Experiments and interventions", '"Big Data"', "Elections and campaigns", "Writing a paper", "Data and the judiciary", "Election forecasting", "Big problems in social science", "Fixing(?) those problems", "Final presentations", "Final paper due")



table_outline <- 
  tibble(week = c(1, rep(2:14, each = 2), 15), 
         date_column, lecture_topics, 
         reading = as.character(NA), slides = as.character(NA), 
         assignment = as.character(NA)) %>% 
  print(n = nrow(.))


```


```{r print-table}
# knitr::kable(full_table)
kable(table_outline) %>% print()

```